module: EntwineTest
title: Testing suite for Apple’s Combine Framework
theme: fullwidth 
skip_undocumented: true
readme: ./Entwine/Assets/EntwineTest/README.md
hide_documentation_coverage: true
output: EntwineTestDocs
xcodebuild_arguments:
  - -workspace
  - Entwine/.swiftpm/xcode/package.xcworkspace
  - -scheme
  - EntwineTest
author: Tristan Celder
author_url: https://twitter.com/_goluxo
github_url: https://github.com/tcldr